import { FieldDefinitionDto } from '@campus-os/types';

/**
 * 80+ Categorized Master Field Library Catalog
 * Covering Canonical, Standard, and ERP Smart Master fields across 17 categories.
 */
export const MASTER_FIELD_LIBRARY_CATALOG: Array<Omit<FieldDefinitionDto, 'id' | 'createdAt' | 'updatedAt'> & { id?: string }> = [
  // ── 1. STUDENT BASIC INFORMATION ──────────────────────────────────
  {
    code: 'STD_FIRST_NAME',
    canonicalKey: 'STUDENT_FIRST_NAME',
    name: 'First Name',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'First Name',
    defaultPlaceholder: 'Enter student first name',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, minLength: 2, maxLength: 64 },
  },
  {
    code: 'STD_MIDDLE_NAME',
    canonicalKey: 'STUDENT_MIDDLE_NAME',
    name: 'Middle Name',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Middle Name',
    defaultPlaceholder: 'Enter middle name (optional)',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: false, maxLength: 64 },
  },
  {
    code: 'STD_LAST_NAME',
    canonicalKey: 'STUDENT_LAST_NAME',
    name: 'Last Name',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Last Name / Surname',
    defaultPlaceholder: 'Enter student last name',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, minLength: 2, maxLength: 64 },
  },
  {
    code: 'STD_FULL_NAME',
    canonicalKey: 'STUDENT_FULL_NAME',
    name: 'Student Full Name',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Full Official Name (as on official docs)',
    defaultPlaceholder: 'Enter student full official name',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, minLength: 3, maxLength: 128 },
  },
  {
    code: 'STD_PREFERRED_NAME',
    canonicalKey: 'STUDENT_PREFERRED_NAME',
    name: 'Preferred / Call Name',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Preferred Name',
    defaultPlaceholder: 'e.g. Ali',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'STD_DOB',
    canonicalKey: 'STUDENT_DOB',
    name: 'Date of Birth',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'DATE',
    defaultLabel: 'Date of Birth',
    defaultHelpText: 'Used for age-based class eligibility calculation.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'STD_GENDER',
    canonicalKey: 'STUDENT_GENDER',
    name: 'Gender',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'RADIO',
    defaultLabel: 'Gender',
    defaultOptions: [
      { label: 'Male', value: 'MALE' },
      { label: 'Female', value: 'FEMALE' },
      { label: 'Other', value: 'OTHER' },
    ],
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'STD_PLACE_OF_BIRTH',
    canonicalKey: 'STUDENT_POB',
    name: 'Place of Birth',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Place of Birth / City',
    defaultPlaceholder: 'e.g. Karachi',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'STD_NATIONALITY',
    canonicalKey: 'STUDENT_NATIONALITY',
    name: 'Nationality',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    defaultLabel: 'Nationality',
    defaultOptions: [
      { label: 'Pakistani', value: 'Pakistani' },
      { label: 'Overseas Pakistani', value: 'Overseas Pakistani' },
      { label: 'Foreign National', value: 'Foreign National' },
    ],
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'STD_MOTHER_TONGUE',
    canonicalKey: 'STUDENT_MOTHER_TONGUE',
    name: 'Mother Tongue',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Mother Tongue',
    defaultOptions: [
      { label: 'Urdu', value: 'Urdu' },
      { label: 'English', value: 'English' },
      { label: 'Sindhi', value: 'Sindhi' },
      { label: 'Punjabi', value: 'Punjabi' },
      { label: 'Pashto', value: 'Pashto' },
      { label: 'Balochi', value: 'Balochi' },
      { label: 'Other', value: 'Other' },
    ],
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'STD_SECONDARY_LANG',
    canonicalKey: 'STUDENT_SECONDARY_LANG',
    name: 'Secondary Language',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Secondary Language',
    defaultOptions: [
      { label: 'English', value: 'English' },
      { label: 'Urdu', value: 'Urdu' },
      { label: 'Arabic', value: 'Arabic' },
      { label: 'French', value: 'French' },
    ],
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'STD_EMAIL',
    canonicalKey: 'STUDENT_EMAIL',
    name: 'Student Email',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'EMAIL',
    defaultLabel: 'Student Email Address',
    defaultPlaceholder: 'student@example.com',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { emailFormat: true },
  },
  {
    code: 'STD_MOBILE',
    canonicalKey: 'STUDENT_MOBILE',
    name: 'Student Mobile',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Student Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { phoneFormat: true },
  },
  {
    code: 'STD_PHOTO',
    canonicalKey: 'STUDENT_PHOTO',
    name: 'Student Photograph',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'IMAGE_UPLOAD',
    defaultLabel: 'Recent Passport Size Photo',
    defaultHelpText: 'Clear passport-size photograph with white/blue background (Max 5MB).',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { allowedFileTypes: ['.jpg', '.jpeg', '.png'], maxFileSizeMb: 5 },
  },

  // ── 2. IDENTITY INFORMATION ───────────────────────────────────────
  {
    code: 'ID_BFORM',
    canonicalKey: 'IDENTITY_BFORM',
    name: 'B-Form / CRC Number',
    category: 'IDENTITY',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'NADRA B-Form / Child Registration Certificate (CRC)',
    defaultPlaceholder: '42201-1234567-1',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: false, maxLength: 32 },
  },
  {
    code: 'ID_CNIC',
    canonicalKey: 'IDENTITY_CNIC',
    name: 'Student National ID / CNIC / Smart Card',
    category: 'IDENTITY',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'National ID / Smart Card Number',
    defaultPlaceholder: '42201-1234567-1',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'ID_PASSPORT_NO',
    canonicalKey: 'IDENTITY_PASSPORT_NO',
    name: 'Passport Number',
    category: 'IDENTITY',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Passport Number',
    defaultPlaceholder: 'e.g. AB1234567',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'ID_PASSPORT_EXPIRY',
    canonicalKey: 'IDENTITY_PASSPORT_EXPIRY',
    name: 'Passport Expiry Date',
    category: 'IDENTITY',
    origin: 'STANDARD',
    dataType: 'DATE',
    defaultLabel: 'Passport Expiry Date',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 3. APPLICATION & ACADEMIC INFORMATION (ERP SMART FIELDS) ──────
  {
    code: 'ACAD_YEAR_REF',
    canonicalKey: 'ACADEMIC_YEAR',
    name: 'Academic Year / Session',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'ACADEMIC_YEAR',
    defaultLabel: 'Academic Year',
    defaultHelpText: 'Resolved from effective active academic sessions.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ACAD_CAMPUS_REF',
    canonicalKey: 'APPLYING_CAMPUS',
    name: 'Applying Campus / Branch',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'CAMPUS',
    defaultLabel: 'Campus / Branch Applied To',
    defaultHelpText: 'Campus location where the student seeks admission.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ACAD_BOARD_REF',
    canonicalKey: 'BOARD',
    name: 'Curriculum / Board',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'BOARD',
    defaultLabel: 'Examination Board / Curriculum',
    defaultHelpText: 'e.g. Cambridge CIE, Federal Board, Sindh Board.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ACAD_STAGE_REF',
    canonicalKey: 'ACADEMIC_LEVEL',
    name: 'Academic Level / Stage',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'ACADEMIC_LEVEL',
    defaultLabel: 'Academic Level / Stage',
    defaultHelpText: 'e.g. Primary, Middle, Secondary, Higher Secondary.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ACAD_CLASS_REF',
    canonicalKey: 'APPLYING_CLASS',
    name: 'Applying Class / Grade',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'CLASS',
    defaultLabel: 'Applying Class / Grade',
    defaultHelpText: 'Grade level being applied for (e.g. Grade 1, Grade 9).',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ACAD_STREAM',
    canonicalKey: 'ACADEMIC_STREAM',
    name: 'Group / Stream',
    category: 'ADMISSION_ACADEMIC',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Group / Stream (for Secondary & High School)',
    defaultOptions: [
      { label: 'Science (Pre-Medical)', value: 'SCIENCE_PRE_MED' },
      { label: 'Science (Pre-Engineering)', value: 'SCIENCE_PRE_ENG' },
      { label: 'Computer Science (ICS)', value: 'ICS' },
      { label: 'Commerce / Business', value: 'COMMERCE' },
      { label: 'Arts & Humanities', value: 'HUMANITIES' },
      { label: 'General Group', value: 'GENERAL' },
    ],
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'ACAD_ADMISSION_CATEGORY',
    canonicalKey: 'ADMISSION_CATEGORY',
    name: 'Admission Category',
    category: 'ADMISSION_ACADEMIC',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Admission Category',
    defaultOptions: [
      { label: 'Open Merit / Regular', value: 'REGULAR' },
      { label: 'Sibling Concession', value: 'SIBLING' },
      { label: 'Staff / Faculty Ward', value: 'STAFF_CHILD' },
      { label: 'Transfer / Migration', value: 'TRANSFER' },
      { label: 'Scholarship / Need-Based', value: 'SCHOLARSHIP' },
    ],
    isSystemProtected: true,
    isActive: true,
  },

  // ── 4. FATHER INFORMATION ─────────────────────────────────────────
  {
    code: 'FAT_NAME',
    canonicalKey: 'FATHER_NAME',
    name: 'Father Name',
    category: 'FATHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Father Full Name',
    defaultPlaceholder: 'Enter father full name',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, minLength: 2, maxLength: 128 },
  },
  {
    code: 'FAT_CNIC',
    canonicalKey: 'FATHER_CNIC',
    name: 'Father CNIC / National ID',
    category: 'FATHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Father CNIC / National ID',
    defaultPlaceholder: '42201-1234567-1',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, maxLength: 32 },
  },
  {
    code: 'FAT_MOBILE',
    canonicalKey: 'FATHER_MOBILE',
    name: 'Father Mobile Number',
    category: 'FATHER_INFO',
    origin: 'CANONICAL',
    dataType: 'PHONE',
    defaultLabel: 'Father Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, phoneFormat: true },
  },
  {
    code: 'FAT_WHATSAPP',
    canonicalKey: 'FATHER_WHATSAPP',
    name: 'Father WhatsApp Number',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Father WhatsApp Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { phoneFormat: true },
  },
  {
    code: 'FAT_EMAIL',
    canonicalKey: 'FATHER_EMAIL',
    name: 'Father Email Address',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'EMAIL',
    defaultLabel: 'Father Email Address',
    defaultPlaceholder: 'father@example.com',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { emailFormat: true },
  },
  {
    code: 'FAT_OCCUPATION',
    canonicalKey: 'FATHER_OCCUPATION',
    name: 'Father Occupation / Profession',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Father Occupation / Profession',
    defaultPlaceholder: 'e.g. Doctor, Engineer, Business',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'FAT_EMPLOYER',
    canonicalKey: 'FATHER_EMPLOYER',
    name: 'Father Organization / Employer',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Employer / Business Name',
    defaultPlaceholder: 'e.g. ABC Corporation',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'FAT_DESIGNATION',
    canonicalKey: 'FATHER_DESIGNATION',
    name: 'Father Designation',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Father Job Title / Designation',
    defaultPlaceholder: 'e.g. General Manager',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'FAT_MONTHLY_INCOME',
    canonicalKey: 'FATHER_MONTHLY_INCOME',
    name: 'Father Monthly Income',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Father Monthly Income Range',
    defaultOptions: [
      { label: 'Under PKR 50,000', value: 'UNDER_50K' },
      { label: 'PKR 50,000 - 100,000', value: '50K_100K' },
      { label: 'PKR 100,000 - 250,000', value: '100K_250K' },
      { label: 'PKR 250,000 - 500,000', value: '250K_500K' },
      { label: 'Above PKR 500,000', value: 'ABOVE_500K' },
    ],
    isSystemProtected: true,
    isActive: true,
  },

  // ── 5. MOTHER INFORMATION ─────────────────────────────────────────
  {
    code: 'MOT_NAME',
    canonicalKey: 'MOTHER_NAME',
    name: 'Mother Name',
    category: 'MOTHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Mother Full Name',
    defaultPlaceholder: 'Enter mother full name',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, minLength: 2, maxLength: 128 },
  },
  {
    code: 'MOT_CNIC',
    canonicalKey: 'MOTHER_CNIC',
    name: 'Mother CNIC / National ID',
    category: 'MOTHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Mother CNIC / National ID',
    defaultPlaceholder: '42201-1234567-2',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: false, maxLength: 32 },
  },
  {
    code: 'MOT_MOBILE',
    canonicalKey: 'MOTHER_MOBILE',
    name: 'Mother Mobile Number',
    category: 'MOTHER_INFO',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Mother Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { phoneFormat: true },
  },
  {
    code: 'MOT_EMAIL',
    canonicalKey: 'MOTHER_EMAIL',
    name: 'Mother Email Address',
    category: 'MOTHER_INFO',
    origin: 'STANDARD',
    dataType: 'EMAIL',
    defaultLabel: 'Mother Email Address',
    defaultPlaceholder: 'mother@example.com',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { emailFormat: true },
  },
  {
    code: 'MOT_OCCUPATION',
    canonicalKey: 'MOTHER_OCCUPATION',
    name: 'Mother Occupation',
    category: 'MOTHER_INFO',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Mother Occupation / Profession',
    defaultPlaceholder: 'e.g. Housewife, Teacher, Doctor',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 6. GUARDIAN INFORMATION ───────────────────────────────────────
  {
    code: 'GDN_REQUIRED',
    canonicalKey: 'GUARDIAN_REQUIRED',
    name: 'Guardian Other than Parents',
    category: 'GUARDIAN_INFO',
    origin: 'STANDARD',
    dataType: 'BOOLEAN',
    defaultLabel: 'Is Guardian someone other than Father/Mother?',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'GDN_RELATIONSHIP',
    canonicalKey: 'GUARDIAN_RELATIONSHIP',
    name: 'Guardian Relationship',
    category: 'GUARDIAN_INFO',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Relationship to Student',
    defaultOptions: [
      { label: 'Uncle / Aunt', value: 'UNCLE_AUNT' },
      { label: 'Grandparent', value: 'GRANDPARENT' },
      { label: 'Sibling / Brother / Sister', value: 'SIBLING' },
      { label: 'Legal Guardian', value: 'LEGAL_GUARDIAN' },
      { label: 'Other', value: 'OTHER' },
    ],
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'GDN_NAME',
    canonicalKey: 'GUARDIAN_NAME',
    name: 'Guardian Full Name',
    category: 'GUARDIAN_INFO',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Guardian Full Name',
    defaultPlaceholder: 'Enter guardian full name',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'GDN_MOBILE',
    canonicalKey: 'GUARDIAN_MOBILE',
    name: 'Guardian Mobile',
    category: 'GUARDIAN_INFO',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Guardian Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { phoneFormat: true },
  },

  // ── 7. CONTACT & EMERGENCY INFORMATION ────────────────────────────
  {
    code: 'CNT_PRIMARY_MOBILE',
    canonicalKey: 'PRIMARY_CONTACT_MOBILE',
    name: 'Primary Contact Mobile (SMS Alerts)',
    category: 'CONTACT_INFO',
    origin: 'CANONICAL',
    dataType: 'PHONE',
    defaultLabel: 'Primary Contact Mobile for SMS & Updates',
    defaultPlaceholder: '+92 300 1234567',
    defaultHelpText: 'All official SMS notifications and status alerts will be sent here.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, phoneFormat: true },
  },
  {
    code: 'CNT_PRIMARY_EMAIL',
    canonicalKey: 'PRIMARY_CONTACT_EMAIL',
    name: 'Primary Email Address',
    category: 'CONTACT_INFO',
    origin: 'CANONICAL',
    dataType: 'EMAIL',
    defaultLabel: 'Primary Email Address for Admissions',
    defaultPlaceholder: 'parent@example.com',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true, emailFormat: true },
  },
  {
    code: 'CNT_WHATSAPP',
    canonicalKey: 'PRIMARY_WHATSAPP',
    name: 'Primary WhatsApp Number',
    category: 'CONTACT_INFO',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'WhatsApp Number for Updates',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { phoneFormat: true },
  },

  // ── 8. CURRENT RESIDENTIAL ADDRESS (ERP GEOGRAPHY FIELDS) ─────────
  {
    code: 'ADDR_CURR_LINE1',
    canonicalKey: 'CURRENT_ADDRESS_LINE1',
    name: 'Current Address Line 1',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Street Address / House No.',
    defaultPlaceholder: 'House # 123, Street # 4, Block 5',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ADDR_CURR_LINE2',
    canonicalKey: 'CURRENT_ADDRESS_LINE2',
    name: 'Current Address Line 2',
    category: 'CURRENT_ADDRESS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Address Line 2 (Apartment, Suite, Unit)',
    defaultPlaceholder: 'Apartment 4B',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'ADDR_CURR_COUNTRY',
    canonicalKey: 'CURRENT_COUNTRY',
    name: 'Country',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'COUNTRY',
    defaultLabel: 'Country',
    defaultHelpText: 'Cascades to Provinces and Cities.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ADDR_CURR_STATE',
    canonicalKey: 'CURRENT_STATE',
    name: 'State / Province',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'STATE',
    defaultLabel: 'State / Province',
    defaultHelpText: 'Filtered based on selected Country.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ADDR_CURR_CITY',
    canonicalKey: 'CURRENT_CITY',
    name: 'City',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'CITY',
    defaultLabel: 'City',
    defaultHelpText: 'Filtered based on selected State.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'ADDR_CURR_AREA',
    canonicalKey: 'CURRENT_AREA',
    name: 'Area / Zone',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'AREA',
    defaultLabel: 'Area / Zone / Sector',
    defaultHelpText: 'Filtered based on selected City.',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'ADDR_CURR_POSTAL',
    canonicalKey: 'CURRENT_POSTAL_CODE',
    name: 'Postal / ZIP Code',
    category: 'CURRENT_ADDRESS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    masterBinding: 'POSTAL_CODE',
    defaultLabel: 'Postal / ZIP Code',
    defaultPlaceholder: '75300',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 9. PREVIOUS EDUCATION ─────────────────────────────────────────
  {
    code: 'PREV_SCHOOL_NAME',
    canonicalKey: 'PREVIOUS_SCHOOL_NAME',
    name: 'Previous School Name',
    category: 'PREVIOUS_EDUCATION',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Name of Last School Attended',
    defaultPlaceholder: 'e.g. St. Patrick High School',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'PREV_SCHOOL_CITY',
    canonicalKey: 'PREVIOUS_SCHOOL_CITY',
    name: 'Previous School City',
    category: 'PREVIOUS_EDUCATION',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'City of Previous School',
    defaultPlaceholder: 'e.g. Lahore',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'PREV_CLASS',
    canonicalKey: 'PREVIOUS_CLASS_PASSED',
    name: 'Last Class / Grade Passed',
    category: 'PREVIOUS_EDUCATION',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Last Class Passed',
    defaultPlaceholder: 'e.g. Grade 5',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'PREV_PERCENTAGE',
    canonicalKey: 'PREVIOUS_PERCENTAGE',
    name: 'Previous Result / Percentage',
    category: 'PREVIOUS_EDUCATION',
    origin: 'STANDARD',
    dataType: 'DECIMAL',
    defaultLabel: 'Percentage / GPA Obtained',
    defaultPlaceholder: '85.5',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'PREV_SLC_NO',
    canonicalKey: 'PREVIOUS_SLC_NUMBER',
    name: 'School Leaving Certificate (SLC) No.',
    category: 'PREVIOUS_EDUCATION',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'School Leaving Certificate Number',
    defaultPlaceholder: 'SLC-2025-9876',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 10. SIBLING INFORMATION (REPEATABLE GROUP CAPABLE) ────────────
  {
    code: 'SIB_HAS_SIBLING',
    canonicalKey: 'HAS_SIBLING_ENROLLED',
    name: 'Has Sibling Currently Enrolled',
    category: 'SIBLINGS',
    origin: 'STANDARD',
    dataType: 'BOOLEAN',
    defaultLabel: 'Do you have any brother/sister studying in this institution?',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'SIB_STUDENT_ID',
    canonicalKey: 'SIBLING_STUDENT_ID',
    name: 'Sibling Student GR / Roll No',
    category: 'SIBLINGS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Sibling Student ID / GR Number',
    defaultPlaceholder: 'GR-12345',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'SIB_NAME',
    canonicalKey: 'SIBLING_NAME',
    name: 'Sibling Full Name',
    category: 'SIBLINGS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Sibling Full Name',
    defaultPlaceholder: 'Enter sibling full name',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'SIB_CLASS',
    canonicalKey: 'SIBLING_CLASS',
    name: 'Sibling Class & Section',
    category: 'SIBLINGS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Sibling Class / Section',
    defaultPlaceholder: 'e.g. Grade 4 - Blue',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 11. MEDICAL & HEALTH ──────────────────────────────────────────
  {
    code: 'MED_BLOOD_GROUP',
    canonicalKey: 'BLOOD_GROUP',
    name: 'Blood Group',
    category: 'MEDICAL_HEALTH',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Blood Group',
    defaultOptions: [
      { label: 'A+', value: 'A+' },
      { label: 'A-', value: 'A-' },
      { label: 'B+', value: 'B+' },
      { label: 'B-', value: 'B-' },
      { label: 'O+', value: 'O+' },
      { label: 'O-', value: 'O-' },
      { label: 'AB+', value: 'AB+' },
      { label: 'AB-', value: 'AB-' },
    ],
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'MED_ALLERGIES',
    canonicalKey: 'MEDICAL_ALLERGIES',
    name: 'Allergies / Chronic Conditions',
    category: 'MEDICAL_HEALTH',
    origin: 'STANDARD',
    dataType: 'TEXTAREA',
    defaultLabel: 'Known Allergies or Medical Conditions',
    defaultPlaceholder: 'List any allergies (food, dust, medicine) or medical history...',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'MED_EMERGENCY_CONTACT',
    canonicalKey: 'EMERGENCY_CONTACT_PHONE',
    name: 'Emergency Contact Number',
    category: 'MEDICAL_HEALTH',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Emergency Contact Mobile',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { phoneFormat: true },
  },

  // ── 12. TRANSPORT ─────────────────────────────────────────────────
  {
    code: 'TRN_REQUIRED',
    canonicalKey: 'TRANSPORT_REQUIRED',
    name: 'School Transport Required',
    category: 'TRANSPORT',
    origin: 'STANDARD',
    dataType: 'BOOLEAN',
    defaultLabel: 'Require School Van / Bus Transport facility?',
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'TRN_PICKUP_AREA',
    canonicalKey: 'TRANSPORT_PICKUP_AREA',
    name: 'Preferred Pickup / Drop Location',
    category: 'TRANSPORT',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Pickup / Drop Landmark / Area',
    defaultPlaceholder: 'e.g. Near Shell Pump, Main Boulevard',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 13. HOSTEL ────────────────────────────────────────────────────
  {
    code: 'HST_REQUIRED',
    canonicalKey: 'HOSTEL_REQUIRED',
    name: 'Hostel Accommodation Required',
    category: 'HOSTEL',
    origin: 'STANDARD',
    dataType: 'BOOLEAN',
    defaultLabel: 'Require Boarding / Hostel Accommodation?',
    isSystemProtected: true,
    isActive: true,
  },

  // ── 14. DOCUMENTS UPLOAD ──────────────────────────────────────────
  {
    code: 'DOC_BFORM',
    canonicalKey: 'DOC_BFORM_FILE',
    name: 'B-Form / Birth Certificate Copy',
    category: 'DOCUMENTS',
    origin: 'CANONICAL',
    dataType: 'FILE_UPLOAD',
    defaultLabel: 'Upload B-Form / Birth Certificate (PDF or JPG)',
    defaultHelpText: 'Scanned clear copy of NADRA B-Form or Birth Certificate.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { allowedFileTypes: ['.pdf', '.jpg', '.jpeg', '.png'], maxFileSizeMb: 5 },
  },
  {
    code: 'DOC_PARENT_CNIC',
    canonicalKey: 'DOC_PARENT_CNIC_FILE',
    name: 'Father / Mother CNIC Copy',
    category: 'DOCUMENTS',
    origin: 'CANONICAL',
    dataType: 'FILE_UPLOAD',
    defaultLabel: 'Upload Father / Mother CNIC (Front & Back)',
    defaultHelpText: 'Scanned copy of Parent / Guardian CNIC.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { allowedFileTypes: ['.pdf', '.jpg', '.jpeg', '.png'], maxFileSizeMb: 5 },
  },
  {
    code: 'DOC_SLC',
    canonicalKey: 'DOC_SLC_FILE',
    name: 'School Leaving Certificate (SLC)',
    category: 'DOCUMENTS',
    origin: 'STANDARD',
    dataType: 'FILE_UPLOAD',
    defaultLabel: 'Upload Previous School Leaving Certificate',
    defaultHelpText: 'Required for transfer students from other schools.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { allowedFileTypes: ['.pdf', '.jpg', '.jpeg', '.png'], maxFileSizeMb: 5 },
  },
  {
    code: 'DOC_REPORT_CARD',
    canonicalKey: 'DOC_REPORT_CARD_FILE',
    name: 'Previous Annual Result Card',
    category: 'DOCUMENTS',
    origin: 'STANDARD',
    dataType: 'FILE_UPLOAD',
    defaultLabel: 'Upload Last Grade Report / Result Card',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { allowedFileTypes: ['.pdf', '.jpg', '.jpeg', '.png'], maxFileSizeMb: 5 },
  },

  // ── 15. CONSENT & DECLARATION ─────────────────────────────────────
  {
    code: 'DEC_ACCURACY',
    canonicalKey: 'DECLARATION_ACCURACY',
    name: 'Information Accuracy Confirmation',
    category: 'CONSENT_DECLARATION',
    origin: 'CANONICAL',
    dataType: 'CHECKBOX',
    defaultLabel: 'I hereby declare that all information provided in this application is true and complete.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },
  {
    code: 'DEC_TERMS',
    canonicalKey: 'TERMS_ACCEPTED',
    name: 'Terms & Conditions Acceptance',
    category: 'CONSENT_DECLARATION',
    origin: 'CANONICAL',
    dataType: 'CHECKBOX',
    defaultLabel: 'I agree to adhere to the school policies, disciplinary rules, and fee regulations.',
    isSystemProtected: true,
    isActive: true,
    defaultValidation: { required: true },
  },

  // ── 16. OTHER / REMARKS ───────────────────────────────────────────
  {
    code: 'OTH_HEAR_ABOUT_US',
    canonicalKey: 'REFERRAL_SOURCE',
    name: 'How Did You Hear About Us?',
    category: 'OTHER',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'How did you hear about our institution?',
    defaultOptions: [
      { label: 'Friend / Family Recommendation', value: 'FRIEND_FAMILY' },
      { label: 'Social Media (Facebook / Instagram)', value: 'SOCIAL_MEDIA' },
      { label: 'Newspaper / Billboard Ad', value: 'PRINT_AD' },
      { label: 'Existing Student / Alumni', value: 'ALUMNI' },
      { label: 'Google Search / Website', value: 'ONLINE' },
      { label: 'Other', value: 'OTHER' },
    ],
    isSystemProtected: true,
    isActive: true,
  },
  {
    code: 'OTH_SPECIAL_NOTES',
    canonicalKey: 'APPLICANT_SPECIAL_NOTES',
    name: 'Special Remarks / Notes',
    category: 'OTHER',
    origin: 'STANDARD',
    dataType: 'TEXTAREA',
    defaultLabel: 'Additional Notes or Comments',
    defaultPlaceholder: 'Enter any additional details or requirements...',
    isSystemProtected: true,
    isActive: true,
  },
];
