/**
 * Centralized Administration Configuration Registry for CampusOS
 *
 * Drives:
 * - Administration Configuration Control Center (/admin-config)
 * - Global Configuration Search
 * - Category Cards and Detail Panels
 * - User Favorites & Quick Actions
 * - Permission and Scope Filtering
 */

export type ConfigScopeClassification =
  | 'PLATFORM'
  | 'ORGANIZATION'
  | 'SCHOOL'
  | 'BRANCH'
  | 'SHARED_MASTER';

export type ConfigCategoryKey =
  | 'org_setup'
  | 'location_geography'
  | 'academic_setup'
  | 'student_setup'
  | 'hr_employee_setup'
  | 'fee_billing_setup'
  | 'payroll_setup'
  | 'library_setup'
  | 'transport_setup'
  | 'exam_assessment'
  | 'attendance_devices'
  | 'communication_setup'
  | 'general_shared_masters'
  | 'users_access';

export interface ConfigCategoryMeta {
  key: ConfigCategoryKey;
  name: string;
  description: string;
  icon: string;
  sortOrder: number;
}

export interface ConfigItem {
  id: string;
  name: string;
  category: ConfigCategoryKey;
  description: string;
  route: string;
  icon: string;
  keywords: string[];
  requiredPermission: string;
  scopeClassification: ConfigScopeClassification;
  isImplemented: boolean;
  isFavoriteEligible: boolean;
  isQuickActionEligible: boolean;
  sortOrder: number;
}

export const CONFIG_CATEGORIES: ConfigCategoryMeta[] = [
  {
    key: 'org_setup',
    name: 'Organization Setup',
    description: 'Head offices, regions, school types, institutions, and campus branches.',
    icon: '🏛️',
    sortOrder: 1,
  },
  {
    key: 'location_geography',
    name: 'Location & Geography',
    description: 'Shared geographical masters for countries, states, cities, and zones.',
    icon: '🌍',
    sortOrder: 2,
  },
  {
    key: 'academic_setup',
    name: 'Academic Setup',
    description: 'Academic years, boards, classes, sections, groups, and subjects.',
    icon: '🎓',
    sortOrder: 3,
  },
  {
    key: 'student_setup',
    name: 'Student Setup',
    description: 'Student categories, houses, admissions, blood groups, and status masters.',
    icon: '🎒',
    sortOrder: 4,
  },
  {
    key: 'hr_employee_setup',
    name: 'HR & Employee Setup',
    description: 'Departments, designations, job types, qualifications, and employment tiers.',
    icon: '👥',
    sortOrder: 5,
  },
  {
    key: 'fee_billing_setup',
    name: 'Fee & Billing Setup',
    description: 'Fee structures, fee heads, discount policies, fine rules, and banking.',
    icon: '💳',
    sortOrder: 6,
  },
  {
    key: 'payroll_setup',
    name: 'Payroll Setup',
    description: 'Allowances, deductions, salary groups, loan types, and appraisal scales.',
    icon: '💰',
    sortOrder: 7,
  },
  {
    key: 'library_setup',
    name: 'Library Setup',
    description: 'Libraries, book categories, authors, publishers, and catalog masters.',
    icon: '📚',
    sortOrder: 8,
  },
  {
    key: 'transport_setup',
    name: 'Transport Setup',
    description: 'Bus routes, transit stops, fleet vehicles, transporters, and drivers.',
    icon: '🚌',
    sortOrder: 9,
  },
  {
    key: 'exam_assessment',
    name: 'Exam & Assessment',
    description: 'Exam terms, grading scales, assessment schemes, and remarks.',
    icon: '📝',
    sortOrder: 10,
  },
  {
    key: 'attendance_devices',
    name: 'Attendance & Devices',
    description: 'Biometric terminals, RFID machines, mapping rules, and shift policies.',
    icon: '⏱️',
    sortOrder: 11,
  },
  {
    key: 'communication_setup',
    name: 'Communication Setup',
    description: 'Notification templates, announcement categories, and delivery channels.',
    icon: '📢',
    sortOrder: 12,
  },
  {
    key: 'general_shared_masters',
    name: 'General / Shared Masters',
    description: 'Document types, national ID types, relationships, and attachments.',
    icon: '⚙️',
    sortOrder: 13,
  },
  {
    key: 'users_access',
    name: 'Users & Access',
    description: 'Administration users, custom roles, permission ceilings, and data scopes.',
    icon: '🛡️',
    sortOrder: 14,
  },
];

export const CONFIG_REGISTRY: ConfigItem[] = [
  // ── 1. Organization Setup (Implemented) ───────────────────────────
  {
    id: 'org_head_offices',
    name: 'Head Offices',
    category: 'org_setup',
    description: 'Manage central apex administration headquarters and apex contacts.',
    route: '/admin-config/head-offices',
    icon: '🏛️',
    keywords: ['head office', 'hq', 'headquarters', 'central', 'apex', 'governance'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: true,
    isFavoriteEligible: true,
    isQuickActionEligible: true,
    sortOrder: 1,
  },
  {
    id: 'org_regions',
    name: 'Regional Offices',
    category: 'org_setup',
    description: 'Manage regional directorates overseeing regional school clusters.',
    route: '/admin-config/regions',
    icon: '🏢',
    keywords: ['regions', 'regional office', 'directorate', 'division', 'zone'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: true,
    isFavoriteEligible: true,
    isQuickActionEligible: true,
    sortOrder: 2,
  },
  {
    id: 'org_school_types',
    name: 'School Types',
    category: 'org_setup',
    description: 'Define pedagogical categories such as K-12, High School, Montessori, College.',
    route: '/admin-config/school-types',
    icon: '🏷️',
    keywords: ['school types', 'type', 'k12', 'primary', 'secondary', 'category'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: true,
    isFavoriteEligible: true,
    isQuickActionEligible: true,
    sortOrder: 3,
  },
  {
    id: 'org_schools',
    name: 'Schools',
    category: 'org_setup',
    description: 'Manage primary educational institutions and operational school entities.',
    route: '/admin-config/schools',
    icon: '🏫',
    keywords: ['schools', 'institution', 'college', 'academy', 'campus'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: true,
    isFavoriteEligible: true,
    isQuickActionEligible: true,
    sortOrder: 4,
  },
  {
    id: 'org_branches',
    name: 'Branches / Campuses',
    category: 'org_setup',
    description: 'Manage operational branch locations, sorting orders, and branch admins.',
    route: '/admin-config/branches',
    icon: '📍',
    keywords: ['branches', 'campus', 'campuses', 'locations', 'sort order', 'branch admin'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: true,
    isFavoriteEligible: true,
    isQuickActionEligible: true,
    sortOrder: 5,
  },
  {
    id: 'org_hierarchy',
    name: 'Organization Hierarchy',
    category: 'org_setup',
    description: 'Visual interactive hierarchy tree and variable-depth node explorer.',
    route: '/admin-config/hierarchy',
    icon: '🌲',
    keywords: ['hierarchy', 'tree', 'org chart', 'nodes', 'structure'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },
  {
    id: 'org_cost_centers',
    name: 'Cost Centers',
    category: 'org_setup',
    description: 'Manage organizational financial units and multi-branch accounting allocations.',
    route: '/admin-config/cost-centers',
    icon: '💼',
    keywords: ['cost centers', 'budget', 'finance', 'accounting unit'],
    requiredPermission: 'MANAGE_ORGANIZATION',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 7,
  },

  // ── 2. Location & Geography (Shared Masters) ───────────────────────
  {
    id: 'loc_countries',
    name: 'Countries',
    category: 'location_geography',
    description: 'Country codes, dial codes, currency formats, and international standards.',
    route: '/admin-config/countries',
    icon: '🌐',
    keywords: ['countries', 'country', 'international', 'nation'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'loc_provinces',
    name: 'States / Provinces',
    category: 'location_geography',
    description: 'Federal states, provinces, and regional territorial subdivisions.',
    route: '/admin-config/provinces',
    icon: '🗺️',
    keywords: ['provinces', 'states', 'regions', 'territory'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'loc_cities',
    name: 'Cities',
    category: 'location_geography',
    description: 'Municipalities, metropolitan cities, and postal regions.',
    route: '/admin-config/cities',
    icon: '🏙️',
    keywords: ['cities', 'city', 'town', 'municipality'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'loc_areas',
    name: 'Areas / Zones',
    category: 'location_geography',
    description: 'Local neighborhood zones, sectors, and delivery postal catchments.',
    route: '/admin-config/areas',
    icon: '📌',
    keywords: ['areas', 'zones', 'sectors', 'localities'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'loc_postal_codes',
    name: 'Postal Codes',
    category: 'location_geography',
    description: 'ZIP and postal code registries linked to cities and areas.',
    route: '/admin-config/postal-codes',
    icon: '📮',
    keywords: ['postal codes', 'zip', 'zipcode', 'postcode'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },

  // ── 3. Academic Setup ─────────────────────────────────────────────
  {
    id: 'acad_years',
    name: 'Academic Years',
    category: 'academic_setup',
    description: 'Fiscal and academic session timelines (e.g. 2026-2027, Spring 2026).',
    route: '/admin-config/academic-years',
    icon: '📅',
    keywords: ['academic years', 'session', 'term', 'school year'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'acad_boards',
    name: 'Education Boards',
    category: 'academic_setup',
    description: 'Affiliated educational boards (Cambridge, Federal, BISE, IB, Oxford).',
    route: '/admin-config/education-boards',
    icon: '📜',
    keywords: ['education boards', 'bise', 'cambridge', 'ib', 'oxford', 'matric'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'acad_classes',
    name: 'Classes / Grades',
    category: 'academic_setup',
    description: 'Class levels from Pre-Nursery, Grade 1 through A-Levels and Grade 12.',
    route: '/admin-config/classes',
    icon: '🏫',
    keywords: ['classes', 'grades', 'levels', 'standards'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'acad_sections',
    name: 'Sections',
    category: 'academic_setup',
    description: 'Classroom sections (Section A, Green, Red) with capacity limits.',
    route: '/admin-config/sections',
    icon: '🪑',
    keywords: ['sections', 'section', 'division', 'classroom'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'acad_groups',
    name: 'Subject Groups',
    category: 'academic_setup',
    description: 'Curriculum streams: Pre-Medical, Pre-Engineering, Computer Science, Arts.',
    route: '/admin-config/subject-groups',
    icon: '🔬',
    keywords: ['groups', 'streams', 'tracks', 'science', 'arts', 'commerce'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'acad_subjects',
    name: 'Subjects',
    category: 'academic_setup',
    description: 'Course subjects, syllabus codes, credit weights, and elective categories.',
    route: '/admin-config/subjects',
    icon: '📖',
    keywords: ['subjects', 'courses', 'curriculum', 'mathematics', 'english'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },
  {
    id: 'acad_languages',
    name: 'Languages',
    category: 'academic_setup',
    description: 'Medium of instruction and foreign language offerings.',
    route: '/admin-config/languages',
    icon: '🗣️',
    keywords: ['languages', 'instruction', 'urdu', 'english', 'arabic'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 7,
  },
  {
    id: 'acad_capacity',
    name: 'Class Capacity Rules',
    category: 'academic_setup',
    description: 'Student-to-teacher ratio benchmarks and maximum classroom limits.',
    route: '/admin-config/class-capacity',
    icon: '📏',
    keywords: ['class capacity', 'student ratio', 'limits', 'intake'],
    requiredPermission: 'MANAGE_ACADEMICS',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 8,
  },

  // ── 4. Student Setup ──────────────────────────────────────────────
  {
    id: 'std_categories',
    name: 'Student Categories',
    category: 'student_setup',
    description: 'Categories such as General, Staff Child, Scholarship, Boarder.',
    route: '/admin-config/student-categories',
    icon: '🏷️',
    keywords: ['student categories', 'category', 'quota', 'scholarship'],
    requiredPermission: 'MANAGE_STUDENTS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'std_houses',
    name: 'School Houses',
    category: 'student_setup',
    description: 'Houses for sports, clubs, discipline points, and inter-house events.',
    route: '/admin-config/houses',
    icon: '🚩',
    keywords: ['houses', 'teams', 'clubs', 'sports house'],
    requiredPermission: 'MANAGE_STUDENTS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'std_admission_categories',
    name: 'Admission Categories',
    category: 'student_setup',
    description: 'Regular admission, Transfer, Sibling, Sports quota classifications.',
    route: '/admin-config/admission-categories',
    icon: '📝',
    keywords: ['admission categories', 'intake', 'enrollment type'],
    requiredPermission: 'MANAGE_STUDENTS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'std_blood_groups',
    name: 'Blood Groups',
    category: 'student_setup',
    description: 'Master list of medical blood groups for student and staff health profiles.',
    route: '/admin-config/blood-groups',
    icon: '🩸',
    keywords: ['blood groups', 'medical', 'health'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'std_religions',
    name: 'Religions',
    category: 'student_setup',
    description: 'Religious denominations master for curriculum and official census data.',
    route: '/admin-config/religions',
    icon: '🕊️',
    keywords: ['religion', 'denominations', 'census'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'std_status',
    name: 'Student Statuses',
    category: 'student_setup',
    description: 'Enrolled, Suspended, Graduated, Transferred, and Inactive student states.',
    route: '/admin-config/student-statuses',
    icon: '🚦',
    keywords: ['student status', 'enrollment status', 'active', 'alumni'],
    requiredPermission: 'MANAGE_STUDENTS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },
  {
    id: 'std_withdrawal_reasons',
    name: 'Withdrawal Reasons',
    category: 'student_setup',
    description: 'Standardized exit reasons for school leaving certificates and analytics.',
    route: '/admin-config/withdrawal-reasons',
    icon: '🚪',
    keywords: ['withdrawal reasons', 'leaving certificate', 'exit', 'dropout'],
    requiredPermission: 'MANAGE_STUDENTS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 7,
  },

  // ── 5. HR & Employee Setup ────────────────────────────────────────
  {
    id: 'hr_departments',
    name: 'Departments',
    category: 'hr_employee_setup',
    description: 'Academic departments (Sciences, Humanities) and administrative wings.',
    route: '/admin-config/departments',
    icon: '🏢',
    keywords: ['departments', 'faculty', 'wings', 'divisions'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'hr_designations',
    name: 'Designations',
    category: 'hr_employee_setup',
    description: 'Principal, Senior Teacher, Lab Assistant, Accountant job titles.',
    route: '/admin-config/designations',
    icon: '👔',
    keywords: ['designations', 'job titles', 'roles', 'posts'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'hr_designation_hierarchy',
    name: 'Designation Hierarchy',
    category: 'hr_employee_setup',
    description: 'Reporting lines, grade levels, and managerial hierarchy trees.',
    route: '/admin-config/designation-hierarchy',
    icon: '🪜',
    keywords: ['designation hierarchy', 'reporting line', 'grades', 'seniority'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'hr_job_types',
    name: 'Job Types',
    category: 'hr_employee_setup',
    description: 'Permanent, Contractual, Visiting, Probation, and Intern contracts.',
    route: '/admin-config/job-types',
    icon: '📋',
    keywords: ['job types', 'contract type', 'permanent', 'visiting'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'hr_job_statuses',
    name: 'Job Statuses',
    category: 'hr_employee_setup',
    description: 'Active, On Leave, Resigned, Retired, Terminated employment status.',
    route: '/admin-config/job-statuses',
    icon: '📊',
    keywords: ['job status', 'employment status', 'resigned', 'active'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'hr_employee_categories',
    name: 'Employee Categories',
    category: 'hr_employee_setup',
    description: 'Teaching Staff, Administrative Staff, Support Staff, Executive.',
    route: '/admin-config/employee-categories',
    icon: '🧑‍🏫',
    keywords: ['employee categories', 'teaching', 'non-teaching', 'staff category'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },
  {
    id: 'hr_qualifications',
    name: 'Qualifications',
    category: 'hr_employee_setup',
    description: 'Degree types (PhD, M.Phil, Masters, B.Ed, BS) and certifications.',
    route: '/admin-config/qualifications',
    icon: '📜',
    keywords: ['qualifications', 'degrees', 'education', 'certificates'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 7,
  },
  {
    id: 'hr_marital_status',
    name: 'Marital Statuses',
    category: 'hr_employee_setup',
    description: 'Single, Married, Widowed, Divorced options for HR records.',
    route: '/admin-config/marital-statuses',
    icon: '💍',
    keywords: ['marital status', 'single', 'married'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 8,
  },
  {
    id: 'hr_employment_types',
    name: 'Employment Types',
    category: 'hr_employee_setup',
    description: 'Full-time, Part-time, Shift-based, Remote working arrangements.',
    route: '/admin-config/employment-types',
    icon: '⏳',
    keywords: ['employment types', 'full-time', 'part-time', 'hours'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 9,
  },

  // ── 6. Fee & Billing Setup ────────────────────────────────────────
  {
    id: 'fee_types',
    name: 'Fee Types',
    category: 'fee_billing_setup',
    description: 'Tuition Fee, Admission Fee, Exam Fee, Transport Fee, Lab Charges.',
    route: '/admin-config/fee-types',
    icon: '🧾',
    keywords: ['fee types', 'tuition', 'admission fee', 'charges'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'fee_heads',
    name: 'Fee Heads / Names',
    category: 'fee_billing_setup',
    description: 'Ledger-linked fee item nomenclature and income chart of accounts.',
    route: '/admin-config/fee-heads',
    icon: '🏷️',
    keywords: ['fee heads', 'ledger', 'accounting', 'billing head'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'fee_discount_categories',
    name: 'Discount Categories',
    category: 'fee_billing_setup',
    description: 'Sibling concession, Need-based aid, Merit scholarship, Staff discount.',
    route: '/admin-config/fee-discounts',
    icon: '🎁',
    keywords: ['discount categories', 'scholarship', 'sibling discount', 'concession'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'fee_fine_rules',
    name: 'Fine & Late Fee Rules',
    category: 'fee_billing_setup',
    description: 'Late payment penalty slabs, grace periods, and surcharge calculations.',
    route: '/admin-config/fine-rules',
    icon: '⚠️',
    keywords: ['fine rules', 'late fee', 'penalty', 'due date surcharge'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'fee_payment_methods',
    name: 'Payment Methods',
    category: 'fee_billing_setup',
    description: 'Bank Challan, 1Link Online, Kuickpay, Debit/Credit Card, Cash, Cheque.',
    route: '/admin-config/payment-methods',
    icon: '💳',
    keywords: ['payment methods', 'challan', 'online payment', '1link', 'kuickpay'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'fee_banks',
    name: 'Banks Master',
    category: 'fee_billing_setup',
    description: 'Commercial partner banks for fee collection and payroll disbursement.',
    route: '/admin-config/banks',
    icon: '🏦',
    keywords: ['banks', 'commercial bank', 'financial institution'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },
  {
    id: 'fee_bank_branches',
    name: 'Bank Branches',
    category: 'fee_billing_setup',
    description: 'Specific bank branch codes, account numbers, and IBAN mappings.',
    route: '/admin-config/bank-branches',
    icon: '🏢',
    keywords: ['bank branches', 'iban', 'account number', 'branch code'],
    requiredPermission: 'MANAGE_FINANCE',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 7,
  },

  // ── 7. Payroll Setup ──────────────────────────────────────────────
  {
    id: 'pay_allowances',
    name: 'Allowances',
    category: 'payroll_setup',
    description: 'House rent, Medical, Conveyance, Utility, and Special teaching allowances.',
    route: '/admin-config/allowances',
    icon: '➕',
    keywords: ['allowances', 'hra', 'medical allowance', 'salary addition'],
    requiredPermission: 'MANAGE_PAYROLL',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'pay_deductions',
    name: 'Deductions',
    category: 'payroll_setup',
    description: 'Income tax slabs, EOBI, Provident fund, and Unpaid leave deductions.',
    route: '/admin-config/deductions',
    icon: '➖',
    keywords: ['deductions', 'tax', 'eobi', 'provident fund', 'salary cut'],
    requiredPermission: 'MANAGE_PAYROLL',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'pay_groups',
    name: 'Salary Groups',
    category: 'payroll_setup',
    description: 'Pay scales and compensation structure templates by employee tier.',
    route: '/admin-config/salary-groups',
    icon: '📊',
    keywords: ['salary groups', 'pay scale', 'compensation', 'grade package'],
    requiredPermission: 'MANAGE_PAYROLL',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'pay_loan_types',
    name: 'Staff Loan Types',
    category: 'payroll_setup',
    description: 'Advance salary, Emergency loan, Provident fund advance policies.',
    route: '/admin-config/loan-types',
    icon: '🤝',
    keywords: ['loan types', 'advance salary', 'staff loan'],
    requiredPermission: 'MANAGE_PAYROLL',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'pay_leave_types',
    name: 'Leave Types',
    category: 'payroll_setup',
    description: 'Casual, Sick, Annual, Maternity, Study, and Hajj leave quotas.',
    route: '/admin-config/leave-types',
    icon: '🏖️',
    keywords: ['leave types', 'annual leave', 'sick leave', 'quota'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'pay_appraisal_scores',
    name: 'Appraisal Scores',
    category: 'payroll_setup',
    description: 'KPI weighting metrics and annual performance evaluation criteria.',
    route: '/admin-config/appraisal-scores',
    icon: '⭐',
    keywords: ['appraisal scores', 'evaluation', 'kpi', 'performance review'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },
  {
    id: 'pay_rating_scales',
    name: 'Rating Scales',
    category: 'payroll_setup',
    description: 'Standard 5-point and 10-point appraisal scale definitions.',
    route: '/admin-config/rating-scales',
    icon: '📈',
    keywords: ['rating scales', 'scores', 'grading matrix'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 7,
  },

  // ── 8. Library Setup ──────────────────────────────────────────────
  {
    id: 'lib_libraries',
    name: 'Libraries',
    category: 'library_setup',
    description: 'Central library and branch reading room physical locations.',
    route: '/admin-config/libraries',
    icon: '🏛️',
    keywords: ['libraries', 'reading room', 'book stock'],
    requiredPermission: 'MANAGE_LIBRARY',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'lib_book_types',
    name: 'Book Types',
    category: 'library_setup',
    description: 'Reference, Textbook, Fiction, Periodical, Journal classifications.',
    route: '/admin-config/book-types',
    icon: '📖',
    keywords: ['book types', 'reference', 'textbook', 'periodical'],
    requiredPermission: 'MANAGE_LIBRARY',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'lib_book_categories',
    name: 'Book Categories',
    category: 'library_setup',
    description: 'Dewey Decimal and custom genre catalog taxonomy.',
    route: '/admin-config/book-categories',
    icon: '🏷️',
    keywords: ['book categories', 'genre', 'dewey decimal'],
    requiredPermission: 'MANAGE_LIBRARY',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'lib_authors',
    name: 'Authors',
    category: 'library_setup',
    description: 'Book authors directory and catalog bibliographic cross-references.',
    route: '/admin-config/authors',
    icon: '✍️',
    keywords: ['authors', 'writers', 'biography'],
    requiredPermission: 'MANAGE_LIBRARY',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'lib_publishers',
    name: 'Publishers',
    category: 'library_setup',
    description: 'Publishing houses and international ISBN vendor registers.',
    route: '/admin-config/publishers',
    icon: '🏢',
    keywords: ['publishers', 'press', 'isbn', 'publications'],
    requiredPermission: 'MANAGE_LIBRARY',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'lib_book_subjects',
    name: 'Book Subjects',
    category: 'library_setup',
    description: 'Topical subject tags for library search and discovery.',
    route: '/admin-config/book-subjects',
    icon: '📑',
    keywords: ['book subjects', 'topics', 'indexing'],
    requiredPermission: 'MANAGE_LIBRARY',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },

  // ── 9. Transport Setup ────────────────────────────────────────────
  {
    id: 'trans_routes',
    name: 'Transport Routes',
    category: 'transport_setup',
    description: 'Morning and evening student transit route paths and fare zones.',
    route: '/admin-config/transport-routes',
    icon: '🗺️',
    keywords: ['routes', 'bus route', 'transit path', 'van route'],
    requiredPermission: 'MANAGE_TRANSPORT',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'trans_stops',
    name: 'Transit Stops',
    category: 'transport_setup',
    description: 'Designated pick-up/drop-off landmarks and geo-coordinates.',
    route: '/admin-config/transit-stops',
    icon: '🚏',
    keywords: ['stops', 'pick up point', 'bus stop'],
    requiredPermission: 'MANAGE_TRANSPORT',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'trans_vehicles',
    name: 'Vehicles Fleet',
    category: 'transport_setup',
    description: 'School buses, vans, coaster fleet numbers, and registration details.',
    route: '/admin-config/vehicles',
    icon: '🚌',
    keywords: ['vehicles', 'buses', 'fleet', 'vans'],
    requiredPermission: 'MANAGE_TRANSPORT',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'trans_vehicle_types',
    name: 'Vehicle Types',
    category: 'transport_setup',
    description: 'Bus 52-Seater, Coaster 28-Seater, Hiace Van, Car models.',
    route: '/admin-config/vehicle-types',
    icon: '🚐',
    keywords: ['vehicle types', 'coaster', 'hiace', 'bus type'],
    requiredPermission: 'MANAGE_TRANSPORT',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'trans_transporters',
    name: 'Transporters / Vendors',
    category: 'transport_setup',
    description: 'Third-party transport contractor companies and SLA contracts.',
    route: '/admin-config/transporters',
    icon: '🏢',
    keywords: ['transporters', 'contractors', 'fleet vendors'],
    requiredPermission: 'MANAGE_TRANSPORT',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
  {
    id: 'trans_drivers',
    name: 'Drivers & Conductors',
    category: 'transport_setup',
    description: 'Commercial driving licenses, emergency contacts, and background checks.',
    route: '/admin-config/drivers',
    icon: '🧑‍✈️',
    keywords: ['drivers', 'conductors', 'license', 'transport staff'],
    requiredPermission: 'MANAGE_TRANSPORT',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 6,
  },

  // ── 10. Exam & Assessment ─────────────────────────────────────────
  {
    id: 'exam_types',
    name: 'Exam Types',
    category: 'exam_assessment',
    description: 'Midterm, Final Term, Monthly Quiz, Send-Up, Mock Exam series.',
    route: '/admin-config/exam-types',
    icon: '📝',
    keywords: ['exam types', 'midterm', 'final exam', 'quiz', 'mock'],
    requiredPermission: 'MANAGE_EXAMS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'exam_grades',
    name: 'Grades & Marks Slabs',
    category: 'exam_assessment',
    description: 'A+, A, B, C, D, F score percentage thresholds and GPA points.',
    route: '/admin-config/grades',
    icon: '🅰️',
    keywords: ['grades', 'gpa', 'marks slabs', 'percentage'],
    requiredPermission: 'MANAGE_EXAMS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'exam_grading_schemes',
    name: 'Grading Schemes',
    category: 'exam_assessment',
    description: 'Cambridge O/A-level 9-point scale vs. FBISE 1000-mark matrices.',
    route: '/admin-config/grading-schemes',
    icon: '📊',
    keywords: ['grading schemes', 'cambridge grading', 'fbise scheme'],
    requiredPermission: 'MANAGE_EXAMS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'exam_remarks',
    name: 'Report Card Remarks',
    category: 'exam_assessment',
    description: 'Standardized teacher performance comments and behavioral templates.',
    route: '/admin-config/exam-remarks',
    icon: '💬',
    keywords: ['remarks', 'report card comments', 'behavior remarks'],
    requiredPermission: 'MANAGE_EXAMS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'exam_assessment_types',
    name: 'Assessment Types',
    category: 'exam_assessment',
    description: 'Formative quizzes, Summative papers, Lab practicals, Oral tests.',
    route: '/admin-config/assessment-types',
    icon: '🧪',
    keywords: ['assessment types', 'practical', 'formative', 'summative'],
    requiredPermission: 'MANAGE_EXAMS',
    scopeClassification: 'SCHOOL',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },

  // ── 11. Attendance & Devices ──────────────────────────────────────
  {
    id: 'att_devices',
    name: 'Attendance Devices',
    category: 'attendance_devices',
    description: 'Biometric face/fingerprint terminals and RFID door gateways.',
    route: '/admin-config/attendance-devices',
    icon: '📟',
    keywords: ['attendance devices', 'biometric', 'zkteco', 'rfid reader'],
    requiredPermission: 'MANAGE_DEVICES',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'att_device_types',
    name: 'Device Models / Types',
    category: 'attendance_devices',
    description: 'Supported hardware protocols: ZKTeco Push, Hikvision, Dahua, Manual.',
    route: '/admin-config/device-types',
    icon: '🔌',
    keywords: ['device types', 'protocols', 'zkteco', 'hikvision'],
    requiredPermission: 'MANAGE_DEVICES',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'att_device_mapping',
    name: 'Device Branch Mapping',
    category: 'attendance_devices',
    description: 'Assign physical devices to specific campus gates and branch networks.',
    route: '/admin-config/device-mapping',
    icon: '🗺️',
    keywords: ['device mapping', 'gate', 'campus device link'],
    requiredPermission: 'MANAGE_DEVICES',
    scopeClassification: 'BRANCH',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'att_rules',
    name: 'Attendance & Shift Rules',
    category: 'attendance_devices',
    description: 'Grace minutes, half-day cutoff, late mark deduction thresholds.',
    route: '/admin-config/attendance-rules',
    icon: '⏰',
    keywords: ['attendance rules', 'shifts', 'grace time', 'late policy'],
    requiredPermission: 'MANAGE_HR',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },

  // ── 12. Communication Setup ───────────────────────────────────────
  {
    id: 'comm_notice_categories',
    name: 'Notice Categories',
    category: 'communication_setup',
    description: 'Academic alerts, Fee reminders, Holiday circulars, Event invites.',
    route: '/admin-config/notice-categories',
    icon: '🏷️',
    keywords: ['notice categories', 'circular', 'announcements'],
    requiredPermission: 'MANAGE_COMMUNICATIONS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'comm_notice_types',
    name: 'Notice Urgency Types',
    category: 'communication_setup',
    description: 'Standard circular, Urgent broadcast, Emergency alert levels.',
    route: '/admin-config/notice-types',
    icon: '🚨',
    keywords: ['notice types', 'emergency', 'broadcast priority'],
    requiredPermission: 'MANAGE_COMMUNICATIONS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'comm_templates',
    name: 'Message Templates',
    category: 'communication_setup',
    description: 'SMS, WhatsApp, and Email dynamic tags (e.g. {{student_name}}, {{fee_due}}).',
    route: '/admin-config/message-templates',
    icon: '✉️',
    keywords: ['templates', 'sms template', 'whatsapp template', 'email template'],
    requiredPermission: 'MANAGE_COMMUNICATIONS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'comm_channels',
    name: 'Communication Gateways',
    category: 'communication_setup',
    description: 'SMS Gateway (Twilio/Telenor/Zong), WhatsApp Cloud API, SMTP credentials.',
    route: '/admin-config/communication-channels',
    icon: '📡',
    keywords: ['channels', 'sms gateway', 'smtp', 'whatsapp api'],
    requiredPermission: 'MANAGE_COMMUNICATIONS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },

  // ── 13. General / Shared Masters ──────────────────────────────────
  {
    id: 'gen_doc_types',
    name: 'Document Types',
    category: 'general_shared_masters',
    description: 'Birth Certificate, B-Form, Leaving Certificate, CNIC, Degree scans.',
    route: '/admin-config/document-types',
    icon: '📄',
    keywords: ['document types', 'birth certificate', 'b-form', 'cnic', 'degrees'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'gen_relationship_types',
    name: 'Relationship Types',
    category: 'general_shared_masters',
    description: 'Father, Mother, Guardian, Uncle, Sibling relationship classifications.',
    route: '/admin-config/relationship-types',
    icon: '👨‍👩‍👧',
    keywords: ['relationship types', 'guardian', 'father', 'mother'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'gen_id_types',
    name: 'National ID Types',
    category: 'general_shared_masters',
    description: 'CNIC, NICOP, Passport, B-Form, Driving License verification formats.',
    route: '/admin-config/id-types',
    icon: '🪪',
    keywords: ['id types', 'cnic', 'passport', 'nicop', 'national identity'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'gen_attachment_cats',
    name: 'Attachment Categories',
    category: 'general_shared_masters',
    description: 'Categorization for digital uploads, fee challans, medical forms.',
    route: '/admin-config/attachment-categories',
    icon: '📎',
    keywords: ['attachment categories', 'uploads', 'files'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'gen_status_reasons',
    name: 'Status & Reason Masters',
    category: 'general_shared_masters',
    description: 'Cross-module cancellation, reversal, suspension, and deactivation reasons.',
    route: '/admin-config/status-reasons',
    icon: '⚖️',
    keywords: ['status reasons', 'deactivation reason', 'cancellation'],
    requiredPermission: 'MANAGE_SHARED_MASTERS',
    scopeClassification: 'SHARED_MASTER',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },

  // ── 14. Users & Access (Permissions) ──────────────────────────────
  {
    id: 'sec_admin_users',
    name: 'Administrative Users',
    category: 'users_access',
    description: 'Manage staff, system administrators, directors, and login credentials.',
    route: '/admin-config/admin-users',
    icon: '👤',
    keywords: ['users', 'staff login', 'credentials', 'admin accounts'],
    requiredPermission: 'MANAGE_USERS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 1,
  },
  {
    id: 'sec_roles',
    name: 'Roles & Profiles',
    category: 'users_access',
    description: 'Create custom roles (Branch Accountant, Vice Principal, Head of Dept).',
    route: '/admin-config/roles',
    icon: '🛡️',
    keywords: ['roles', 'profiles', 'security roles'],
    requiredPermission: 'MANAGE_SECURITY',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 2,
  },
  {
    id: 'sec_permissions',
    name: 'Permissions & Ceilings',
    category: 'users_access',
    description: 'Fine-grained module capabilities and delegation ceiling constraints.',
    route: '/admin-config/permissions',
    icon: '🔑',
    keywords: ['permissions', 'delegation ceiling', 'privileges', 'access rules'],
    requiredPermission: 'MANAGE_SECURITY',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 3,
  },
  {
    id: 'sec_assignments',
    name: 'Node Assignments',
    category: 'users_access',
    description: 'Assign users to specific hierarchy nodes (Head Office, Region, School, Branch).',
    route: '/admin-config/node-assignments',
    icon: '🎯',
    keywords: ['node assignments', 'hierarchy scope', 'branch access', 'campus scope'],
    requiredPermission: 'MANAGE_USERS',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 4,
  },
  {
    id: 'sec_data_scopes',
    name: 'Data Scopes',
    category: 'users_access',
    description: 'Multi-campus reporting scopes and automated subtree data governance.',
    route: '/admin-config/data-scopes',
    icon: '🔭',
    keywords: ['data scopes', 'reporting scope', 'subtree access', 'governance'],
    requiredPermission: 'MANAGE_SECURITY',
    scopeClassification: 'ORGANIZATION',
    isImplemented: false,
    isFavoriteEligible: true,
    isQuickActionEligible: false,
    sortOrder: 5,
  },
];
