import { FieldCategory, FieldDefinitionDto } from '@campus-os/types';

export interface FieldCategoryInfo {
  key: FieldCategory;
  name: string;
  icon: string;
  description: string;
}

export const FIELD_CATEGORIES_INFO: FieldCategoryInfo[] = [
  { key: 'STUDENT_BASIC', name: 'Student Basic Details', icon: '👤', description: 'Name, DOB, gender, nationality, languages, email, mobile, and photo.' },
  { key: 'IDENTITY', name: 'Identity & Legal Documents', icon: '🪪', description: 'B-Form / CRC, National CNIC, Smart Card, and Passport information.' },
  { key: 'ADMISSION_ACADEMIC', name: 'Academic & Applying Class', icon: '🎓', description: 'ERP Smart Master references: Academic Year, Campus, Board, Stage, and Class.' },
  { key: 'FATHER_INFO', name: 'Father Information', icon: '👨', description: 'Father name, CNIC, mobile, WhatsApp, occupation, and income.' },
  { key: 'MOTHER_INFO', name: 'Mother Information', icon: '👩', description: 'Mother name, CNIC, mobile, email, and occupation.' },
  { key: 'GUARDIAN_INFO', name: 'Guardian Information', icon: '🛡️', description: 'Relationship, full name, mobile, and legal guardian details.' },
  { key: 'CONTACT_INFO', name: 'Contact & Emergency Numbers', icon: '📞', description: 'Primary mobile for SMS alerts, primary email, and WhatsApp.' },
  { key: 'CURRENT_ADDRESS', name: 'Residential Address', icon: '🏠', description: 'Street address, Country, State/Province, City, and Area/Zone masters.' },
  { key: 'PREVIOUS_EDUCATION', name: 'Previous School History', icon: '🏫', description: 'Previous school name, city, grade passed, percentage, and SLC number.' },
  { key: 'SIBLINGS', name: 'Sibling Information', icon: '👨‍👧‍👦', description: 'Repeatable sibling records with student ID, name, class, and section.' },
  { key: 'MEDICAL_HEALTH', name: 'Medical & Health Profile', icon: '🩺', description: 'Blood group, allergies, chronic medical conditions, and emergency phone.' },
  { key: 'TRANSPORT', name: 'School Transport Facility', icon: '🚌', description: 'Transport requirement and preferred pickup/drop landmark area.' },
  { key: 'HOSTEL', name: 'Hostel & Boarding', icon: '🛏️', description: 'Hostel accommodation and boarding facility requests.' },
  { key: 'DOCUMENTS', name: 'Document Attachments', icon: '📎', description: 'B-Form copy, Parent CNIC, School Leaving Certificate, and Result Cards.' },
  { key: 'CONSENT_DECLARATION', name: 'Declaration & Policies', icon: '✍️', description: 'Truthfulness declaration and agreement to institutional policies.' },
  { key: 'OTHER', name: 'Other & Miscellaneous', icon: '💬', description: 'Referral source, marketing inquiries, and special parent remarks.' },
];

export const CLIENT_MASTER_FIELD_CATALOG: FieldDefinitionDto[] = [
  // ── 1. Student Basic Information ──────────────────────────────
  {
    id: 'STD_FIRST_NAME',
    code: 'STD_FIRST_NAME',
    canonicalKey: 'STUDENT_FIRST_NAME',
    name: 'First Name',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'First Name',
    defaultPlaceholder: 'Enter student first name',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true, minLength: 2, maxLength: 64 },
  },
  {
    id: 'STD_MIDDLE_NAME',
    code: 'STD_MIDDLE_NAME',
    canonicalKey: 'STUDENT_MIDDLE_NAME',
    name: 'Middle Name',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Middle Name',
    defaultPlaceholder: 'Enter middle name (optional)',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: false },
  },
  {
    id: 'STD_LAST_NAME',
    code: 'STD_LAST_NAME',
    canonicalKey: 'STUDENT_LAST_NAME',
    name: 'Last Name',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Last Name / Surname',
    defaultPlaceholder: 'Enter student last name',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true, minLength: 2 },
  },
  {
    id: 'STD_FULL_NAME',
    code: 'STD_FULL_NAME',
    canonicalKey: 'STUDENT_FULL_NAME',
    name: 'Student Full Name',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Full Official Name (as on official docs)',
    defaultPlaceholder: 'Enter student full official name',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true, minLength: 3 },
  },
  {
    id: 'STD_DOB',
    code: 'STD_DOB',
    canonicalKey: 'STUDENT_DOB',
    name: 'Date of Birth',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'DATE',
    defaultLabel: 'Date of Birth',
    defaultHelpText: 'Used for age-based class eligibility calculation.',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'STD_GENDER',
    code: 'STD_GENDER',
    canonicalKey: 'STUDENT_GENDER',
    name: 'Gender',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'RADIO',
    defaultLabel: 'Gender',
    defaultOptions: [
      { label: 'Male', value: 'MALE' },
      { label: 'Female', value: 'FEMALE' },
      { label: 'Other', value: 'OTHER' },
    ],
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'STD_NATIONALITY',
    code: 'STD_NATIONALITY',
    canonicalKey: 'STUDENT_NATIONALITY',
    name: 'Nationality',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    defaultLabel: 'Nationality',
    defaultOptions: [
      { label: 'Pakistani', value: 'Pakistani' },
      { label: 'Overseas Pakistani', value: 'Overseas Pakistani' },
      { label: 'Foreign National', value: 'Foreign National' },
    ],
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'STD_EMAIL',
    code: 'STD_EMAIL',
    canonicalKey: 'STUDENT_EMAIL',
    name: 'Student Email',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'EMAIL',
    defaultLabel: 'Student Email Address',
    defaultPlaceholder: 'student@example.com',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'STD_MOBILE',
    code: 'STD_MOBILE',
    canonicalKey: 'STUDENT_MOBILE',
    name: 'Student Mobile',
    category: 'STUDENT_BASIC',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Student Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'STD_PHOTO',
    code: 'STD_PHOTO',
    canonicalKey: 'STUDENT_PHOTO',
    name: 'Student Photograph',
    category: 'STUDENT_BASIC',
    origin: 'CANONICAL',
    dataType: 'IMAGE_UPLOAD',
    defaultLabel: 'Recent Passport Size Photo',
    defaultHelpText: 'Clear photograph with plain background (Max 5MB).',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 2. Identity Information ───────────────────────────────────
  {
    id: 'ID_BFORM',
    code: 'ID_BFORM',
    canonicalKey: 'IDENTITY_BFORM',
    name: 'B-Form / CRC Number',
    category: 'IDENTITY',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'NADRA B-Form / Child Registration Certificate (CRC)',
    defaultPlaceholder: '42201-1234567-1',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ID_PASSPORT_NO',
    code: 'ID_PASSPORT_NO',
    canonicalKey: 'IDENTITY_PASSPORT_NO',
    name: 'Passport Number',
    category: 'IDENTITY',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Passport Number',
    defaultPlaceholder: 'AB1234567',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 3. Academic & ERP Smart Fields ────────────────────────────
  {
    id: 'ACAD_YEAR_REF',
    code: 'ACAD_YEAR_REF',
    canonicalKey: 'ACADEMIC_YEAR',
    name: 'Academic Year / Session',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'ACADEMIC_YEAR',
    defaultLabel: 'Academic Session',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ACAD_CAMPUS_REF',
    code: 'ACAD_CAMPUS_REF',
    canonicalKey: 'APPLYING_CAMPUS',
    name: 'Applying Campus / Branch',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'CAMPUS',
    defaultLabel: 'Applying Campus / Branch',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ACAD_BOARD_REF',
    code: 'ACAD_BOARD_REF',
    canonicalKey: 'BOARD',
    name: 'Curriculum / Board',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'BOARD',
    defaultLabel: 'Examination Board / Curriculum',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ACAD_STAGE_REF',
    code: 'ACAD_STAGE_REF',
    canonicalKey: 'ACADEMIC_LEVEL',
    name: 'Academic Level / Stage',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'ACADEMIC_LEVEL',
    defaultLabel: 'Academic Level / Stage',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ACAD_CLASS_REF',
    code: 'ACAD_CLASS_REF',
    canonicalKey: 'APPLYING_CLASS',
    name: 'Applying Class / Grade',
    category: 'ADMISSION_ACADEMIC',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'CLASS',
    defaultLabel: 'Applying Class / Grade',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },

  // ── 4. Father Information ─────────────────────────────────────
  {
    id: 'FAT_NAME',
    code: 'FAT_NAME',
    canonicalKey: 'FATHER_NAME',
    name: 'Father Name',
    category: 'FATHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Father Full Name',
    defaultPlaceholder: 'Enter father full name',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'FAT_CNIC',
    code: 'FAT_CNIC',
    canonicalKey: 'FATHER_CNIC',
    name: 'Father CNIC',
    category: 'FATHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Father CNIC / National ID',
    defaultPlaceholder: '42201-1234567-1',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'FAT_MOBILE',
    code: 'FAT_MOBILE',
    canonicalKey: 'FATHER_MOBILE',
    name: 'Father Mobile Number',
    category: 'FATHER_INFO',
    origin: 'CANONICAL',
    dataType: 'PHONE',
    defaultLabel: 'Father Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'FAT_OCCUPATION',
    code: 'FAT_OCCUPATION',
    canonicalKey: 'FATHER_OCCUPATION',
    name: 'Father Occupation',
    category: 'FATHER_INFO',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Father Profession / Occupation',
    defaultPlaceholder: 'e.g. Doctor, Engineer, Businessman',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 5. Mother Information ─────────────────────────────────────
  {
    id: 'MOT_NAME',
    code: 'MOT_NAME',
    canonicalKey: 'MOTHER_NAME',
    name: 'Mother Name',
    category: 'MOTHER_INFO',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Mother Full Name',
    defaultPlaceholder: 'Enter mother full name',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'MOT_MOBILE',
    code: 'MOT_MOBILE',
    canonicalKey: 'MOTHER_MOBILE',
    name: 'Mother Mobile',
    category: 'MOTHER_INFO',
    origin: 'STANDARD',
    dataType: 'PHONE',
    defaultLabel: 'Mother Mobile Number',
    defaultPlaceholder: '+92 300 1234567',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 6. Contact Information ────────────────────────────────────
  {
    id: 'CNT_PRIMARY_MOBILE',
    code: 'CNT_PRIMARY_MOBILE',
    canonicalKey: 'PRIMARY_CONTACT_MOBILE',
    name: 'Primary Contact Mobile (SMS Alerts)',
    category: 'CONTACT_INFO',
    origin: 'CANONICAL',
    dataType: 'PHONE',
    defaultLabel: 'Primary Mobile for SMS Notifications',
    defaultPlaceholder: '+92 300 1234567',
    defaultHelpText: 'All official SMS notifications and updates will be delivered here.',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'CNT_PRIMARY_EMAIL',
    code: 'CNT_PRIMARY_EMAIL',
    canonicalKey: 'PRIMARY_CONTACT_EMAIL',
    name: 'Primary Email Address',
    category: 'CONTACT_INFO',
    origin: 'CANONICAL',
    dataType: 'EMAIL',
    defaultLabel: 'Primary Email Address for Admissions',
    defaultPlaceholder: 'parent@example.com',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },

  // ── 7. Current Address ────────────────────────────────────────
  {
    id: 'ADDR_CURR_LINE1',
    code: 'ADDR_CURR_LINE1',
    canonicalKey: 'CURRENT_ADDRESS_LINE1',
    name: 'Current Address Line 1',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'TEXT',
    defaultLabel: 'Residential Street Address',
    defaultPlaceholder: 'House # 123, Street # 4, Block 5',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ADDR_CURR_COUNTRY',
    code: 'ADDR_CURR_COUNTRY',
    canonicalKey: 'CURRENT_COUNTRY',
    name: 'Country',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'COUNTRY',
    defaultLabel: 'Country',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ADDR_CURR_STATE',
    code: 'ADDR_CURR_STATE',
    canonicalKey: 'CURRENT_STATE',
    name: 'State / Province',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'STATE',
    defaultLabel: 'State / Province',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ADDR_CURR_CITY',
    code: 'ADDR_CURR_CITY',
    canonicalKey: 'CURRENT_CITY',
    name: 'City',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'CITY',
    defaultLabel: 'City',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'ADDR_CURR_AREA',
    code: 'ADDR_CURR_AREA',
    canonicalKey: 'CURRENT_AREA',
    name: 'Area / Zone',
    category: 'CURRENT_ADDRESS',
    origin: 'CANONICAL',
    dataType: 'DROPDOWN',
    masterBinding: 'AREA',
    defaultLabel: 'Area / Zone',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 8. Previous Education ─────────────────────────────────────
  {
    id: 'PREV_SCHOOL_NAME',
    code: 'PREV_SCHOOL_NAME',
    canonicalKey: 'PREVIOUS_SCHOOL_NAME',
    name: 'Previous School Name',
    category: 'PREVIOUS_EDUCATION',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Name of Last School Attended',
    defaultPlaceholder: 'e.g. St. Patrick High School',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 9. Siblings (Repeatable) ──────────────────────────────────
  {
    id: 'SIB_NAME',
    code: 'SIB_NAME',
    canonicalKey: 'SIBLING_NAME',
    name: 'Sibling Name',
    category: 'SIBLINGS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Sibling Full Name',
    defaultPlaceholder: 'Enter sibling name',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'SIB_CLASS',
    code: 'SIB_CLASS',
    canonicalKey: 'SIBLING_CLASS',
    name: 'Sibling Class / Section',
    category: 'SIBLINGS',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Sibling Class / Section',
    defaultPlaceholder: 'e.g. Grade 4 - Blue',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 10. Medical & Health ──────────────────────────────────────
  {
    id: 'MED_BLOOD_GROUP',
    code: 'MED_BLOOD_GROUP',
    canonicalKey: 'BLOOD_GROUP',
    name: 'Blood Group',
    category: 'MEDICAL_HEALTH',
    origin: 'STANDARD',
    dataType: 'DROPDOWN',
    defaultLabel: 'Blood Group',
    defaultOptions: [
      { label: 'A+', value: 'A+' },
      { label: 'A-', value: 'A-' },
      { label: 'B+', value: 'B+' },
      { label: 'B-', value: 'B-' },
      { label: 'O+', value: 'O+' },
      { label: 'O-', value: 'O-' },
      { label: 'AB+', value: 'AB+' },
      { label: 'AB-', value: 'AB-' },
    ],
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'MED_ALLERGIES',
    code: 'MED_ALLERGIES',
    canonicalKey: 'MEDICAL_ALLERGIES',
    name: 'Allergies / Medical Notes',
    category: 'MEDICAL_HEALTH',
    origin: 'STANDARD',
    dataType: 'TEXTAREA',
    defaultLabel: 'Known Allergies or Medical History',
    defaultPlaceholder: 'List any allergies or medical conditions...',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 11. Transport ─────────────────────────────────────────────
  {
    id: 'TRN_REQUIRED',
    code: 'TRN_REQUIRED',
    canonicalKey: 'TRANSPORT_REQUIRED',
    name: 'Transport Required',
    category: 'TRANSPORT',
    origin: 'STANDARD',
    dataType: 'BOOLEAN',
    defaultLabel: 'Require School Transport facility?',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TRN_PICKUP_AREA',
    code: 'TRN_PICKUP_AREA',
    canonicalKey: 'TRANSPORT_PICKUP_AREA',
    name: 'Pickup Landmark / Area',
    category: 'TRANSPORT',
    origin: 'STANDARD',
    dataType: 'TEXT',
    defaultLabel: 'Pickup / Drop Landmark',
    defaultPlaceholder: 'e.g. Near Shell Pump, Main Boulevard',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 12. Documents ─────────────────────────────────────────────
  {
    id: 'DOC_BFORM',
    code: 'DOC_BFORM',
    canonicalKey: 'DOC_BFORM_FILE',
    name: 'B-Form / Birth Certificate Copy',
    category: 'DOCUMENTS',
    origin: 'CANONICAL',
    dataType: 'FILE_UPLOAD',
    defaultLabel: 'Upload B-Form / Birth Certificate',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'DOC_PARENT_CNIC',
    code: 'DOC_PARENT_CNIC',
    canonicalKey: 'DOC_PARENT_CNIC_FILE',
    name: 'Parent CNIC Copy',
    category: 'DOCUMENTS',
    origin: 'CANONICAL',
    dataType: 'FILE_UPLOAD',
    defaultLabel: 'Upload Father / Mother CNIC (Front & Back)',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 13. Consent & Declaration ─────────────────────────────────
  {
    id: 'DEC_ACCURACY',
    code: 'DEC_ACCURACY',
    canonicalKey: 'DECLARATION_ACCURACY',
    name: 'Information Accuracy Declaration',
    category: 'CONSENT_DECLARATION',
    origin: 'CANONICAL',
    dataType: 'CHECKBOX',
    defaultLabel: 'I declare that all information submitted in this application is accurate, true, and complete.',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
  {
    id: 'DEC_TERMS',
    code: 'DEC_TERMS',
    canonicalKey: 'TERMS_ACCEPTED',
    name: 'Terms & Policies Acceptance',
    category: 'CONSENT_DECLARATION',
    origin: 'CANONICAL',
    dataType: 'CHECKBOX',
    defaultLabel: 'I agree to comply with school policies, disciplinary guidelines, and fee structures.',
    isSystemProtected: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    defaultValidation: { required: true },
  },
];

// ════════════════════════════════════════════════════════════════════
// PERSISTENT CUSTOM FIELD STORAGE LAYER
// ════════════════════════════════════════════════════════════════════

const STORAGE_KEY = 'campusos_persisted_custom_fields_v1';

export function getPersistedCustomFields(): FieldDefinitionDto[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('Failed to load custom fields from storage:', err);
    return [];
  }
}

export function savePersistedCustomField(
  data: Partial<FieldDefinitionDto> & { name: string; category: FieldCategory; dataType: any }
): FieldDefinitionDto {
  const existing = getPersistedCustomFields();
  const cleanCode = data.code
    ? data.code.trim().toUpperCase()
    : `CUST_${data.name.trim().replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}_${Date.now().toString().slice(-4)}`;

  const persistentId = data.id || `cust_${Date.now()}_${cleanCode.toLowerCase()}`;

  const newField: FieldDefinitionDto = {
    id: persistentId,
    code: cleanCode,
    canonicalKey: data.canonicalKey || null,
    name: data.name.trim(),
    description: data.description || null,
    category: data.category,
    origin: 'CUSTOM',
    dataType: data.dataType,
    defaultLabel: data.defaultLabel?.trim() || data.name.trim(),
    defaultPlaceholder: data.defaultPlaceholder?.trim() || undefined,
    defaultHelpText: data.defaultHelpText?.trim() || undefined,
    defaultOptions: data.defaultOptions || [],
    defaultValidation: data.defaultValidation || { required: false },
    isSystemProtected: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const updated = [newField, ...existing.filter((f) => f.id !== persistentId)];
  if (typeof window !== 'undefined') {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  }
  return newField;
}

export function updatePersistedCustomField(
  id: string,
  updates: Partial<FieldDefinitionDto>
): FieldDefinitionDto | null {
  const existing = getPersistedCustomFields();
  const target = existing.find((f) => f.id === id);
  if (!target) return null;

  const modified: FieldDefinitionDto = {
    ...target,
    ...updates,
    updatedAt: new Date(),
  };

  const updated = existing.map((f) => (f.id === id ? modified : f));
  if (typeof window !== 'undefined') {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  }
  return modified;
}

export function getMergedFieldCatalog(): FieldDefinitionDto[] {
  const customFields = getPersistedCustomFields();
  return [...CLIENT_MASTER_FIELD_CATALOG, ...customFields];
}

export function checkDuplicateConcept(name: string): { isDuplicate: boolean; message?: string } {
  const clean = name.trim().toLowerCase();
  const matchPatterns: Record<string, string[]> = {
    STUDENT_DOB: ['dob', 'birth', 'date of birth', 'birthdate'],
    STUDENT_FULL_NAME: ['full name', 'student name', 'candidate name'],
    FATHER_MOBILE: ['father mobile', 'father contact', 'father phone'],
    PRIMARY_CONTACT_MOBILE: ['primary mobile', 'primary phone', 'sms mobile'],
    IDENTITY_BFORM: ['b-form', 'bform', 'crc', 'child registration certificate'],
    FATHER_CNIC: ['father cnic', 'father national id', 'father nic'],
    CURRENT_CITY: ['city', 'residential city'],
    APPLYING_CLASS: ['class', 'grade', 'applying grade'],
  };

  for (const [canonicalKey, tokens] of Object.entries(matchPatterns)) {
    if (tokens.some((t) => clean.includes(t))) {
      const canonical = CLIENT_MASTER_FIELD_CATALOG.find((f) => f.canonicalKey === canonicalKey);
      return {
        isDuplicate: true,
        message: `A canonical system field '${canonical?.name || canonicalKey}' already exists for this concept. We recommend selecting it from the Field Library for automated ERP binding.`,
      };
    }
  }

  return { isDuplicate: false };
}
