/**
 * CampusOS — Central Scope Matrix & Permanent Ownership Registry
 *
 * NON-NEGOTIABLE ARCHITECTURE SPECIFICATION:
 * Every entity in CampusOS MUST belong to one of four ScopeModes:
 *
 * 1. GLOBAL:
 *    Platform-wide reference data. Not filtered by tenant or working context.
 *    Examples: countries, currencies, global constants.
 *
 * 2. TENANT_WIDE:
 *    Tenant-level configuration/catalog. Requires `organization_id NOT NULL`.
 *    Not filtered by campus/working context.
 *    Examples: school types, field library, global form templates.
 *
 * 3. HIERARCHY_SCOPED:
 *    Hierarchy-aware configuration masters. Requires `organization_id`, `owner_type`, `owner_id`, `apply_to`,
 *    and multi-campus scope junction (`config_scope_branches`).
 *    Filtered by effective working context (`userAuthorizedScope ∩ workingContextScope`).
 *    Examples: academic years, boards, levels, classes, sections, subjects, languages, form definitions.
 *
 * 4. CAMPUS_REQUIRED:
 *    Durable operational/transactional records.
 *    MUST persist: `organization_id NOT NULL`, `school_id NOT NULL`, `campus_id NOT NULL`.
 *    Strictly filtered and bound to the active working context.
 *    Examples: pre-admissions, admissions, student enrollment, attendance, test candidates, fee transactions.
 */

export type ScopeMode = 'GLOBAL' | 'TENANT_WIDE' | 'HIERARCHY_SCOPED' | 'CAMPUS_REQUIRED';

export interface EntityScopeMatrixEntry {
  module: string;
  pageRoute?: string;
  entityName: string;
  tableName: string;
  scopeMode: ScopeMode;
  hasOrganizationId: boolean;
  hasSchoolId: boolean;
  hasCampusId: boolean;
  hasHierarchyAssignment: boolean;
  isWorkingContextApplied: boolean;
  isBackendEnforced: boolean;
  isDbPersisted: boolean;
  description: string;
}

export const CAMPUS_OS_SCOPE_MATRIX: EntityScopeMatrixEntry[] = [
  // ── 1. PLATFORM & GLOBAL ───────────────────────────────────────────────
  {
    module: 'Geography',
    entityName: 'Country',
    tableName: 'countries',
    scopeMode: 'GLOBAL',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Global standard country dataset',
  },
  {
    module: 'Geography',
    entityName: 'State / Province',
    tableName: 'states',
    scopeMode: 'GLOBAL',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Standard provincial divisions',
  },
  {
    module: 'Geography',
    entityName: 'City',
    tableName: 'cities',
    scopeMode: 'GLOBAL',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Standard city registry',
  },

  // ── 2. TENANT_WIDE MASTERS ────────────────────────────────────────────
  {
    module: 'Organization Setup',
    pageRoute: '/admin-config/school-types',
    entityName: 'School Type',
    tableName: 'school_types',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Organization-wide institutional types (K-12, College, etc.)',
  },
  {
    module: 'Dynamic Forms',
    pageRoute: '/admin-config/field-library',
    entityName: 'Field Definition',
    tableName: 'field_definitions',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Master canonical and custom field library',
  },
  {
    module: 'Dynamic Forms',
    pageRoute: '/admin-config/form-templates',
    entityName: 'Form Template',
    tableName: 'form_templates',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Reusable system and tenant form templates',
  },
  {
    module: 'Organization Hierarchy',
    pageRoute: '/admin-config/head-offices',
    entityName: 'Head Office',
    tableName: 'head_offices',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Central administrative governance units',
  },
  {
    module: 'Organization Hierarchy',
    pageRoute: '/admin-config/regions',
    entityName: 'Region',
    tableName: 'regions',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Regional geographic clusters',
  },
  {
    module: 'Organization Hierarchy',
    pageRoute: '/admin-config/schools',
    entityName: 'School',
    tableName: 'schools',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'School institutional entities',
  },
  {
    module: 'Organization Hierarchy',
    pageRoute: '/admin-config/branches',
    entityName: 'Branch / Campus',
    tableName: 'branches',
    scopeMode: 'TENANT_WIDE',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: true,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: false,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Physical campus operational locations',
  },

  // ── 3. HIERARCHY_SCOPED CONFIGURATION MASTERS ─────────────────────────
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/academic-levels',
    entityName: 'Academic Level / Stage',
    tableName: 'academic_levels',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Academic tiers with multi-campus scope resolution',
  },
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/academic-years',
    entityName: 'Academic Year',
    tableName: 'academic_years',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Academic session calendar definitions',
  },
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/boards',
    entityName: 'Board / Council',
    tableName: 'boards',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Educational examination affiliations',
  },
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/classes',
    entityName: 'Class / Grade',
    tableName: 'classes',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Grade levels and mapped subjects',
  },
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/sections',
    entityName: 'Section',
    tableName: 'sections',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Classroom section allocations',
  },
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/subjects',
    entityName: 'Subject',
    tableName: 'subjects',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Curriculum subjects and mark configs',
  },
  {
    module: 'Academic Masters',
    pageRoute: '/admin-config/languages',
    entityName: 'Language',
    tableName: 'languages',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Language instructional offerings',
  },
  {
    module: 'Dynamic Forms',
    pageRoute: '/admin-config/form-builder',
    entityName: 'Form Definition',
    tableName: 'form_definitions',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Form definitions and versioned schemas',
  },
  {
    module: 'Admissions Process',
    pageRoute: '/admin-config/admission-process',
    entityName: 'Admission Process',
    tableName: 'admission_processes',
    scopeMode: 'HIERARCHY_SCOPED',
    hasOrganizationId: true,
    hasSchoolId: false,
    hasCampusId: false,
    hasHierarchyAssignment: true,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Multi-step admission journey workflow configs',
  },

  // ── 4. CAMPUS_REQUIRED OPERATIONAL TRANSACTIONS ───────────────────────
  {
    module: 'Admissions',
    pageRoute: '/admissions/pre-admissions',
    entityName: 'Pre-Admission Application',
    tableName: 'pre_admissions',
    scopeMode: 'CAMPUS_REQUIRED',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: true,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: true,
    description: 'Online & staff pre-admission applications with immutable snapshot',
  },
  {
    module: 'Admissions',
    pageRoute: '/admissions/tests',
    entityName: 'Admission Test Schedule',
    tableName: 'admission_test_schedules',
    scopeMode: 'CAMPUS_REQUIRED',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: true,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: false, // In-memory phase (subsequent phase for DB migration)
    description: 'Physical/hybrid admission test schedules',
  },
  {
    module: 'Admissions',
    pageRoute: '/admissions/tests',
    entityName: 'Test Candidate Assignment',
    tableName: 'admission_test_assignments',
    scopeMode: 'CAMPUS_REQUIRED',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: true,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: false,
    description: 'Candidate test slotting and attendance',
  },
  {
    module: 'Student Records',
    pageRoute: '/students/enrollments',
    entityName: 'Student Enrollment',
    tableName: 'student_enrollments',
    scopeMode: 'CAMPUS_REQUIRED',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: true,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: false,
    description: 'Official student registration and enrollment',
  },
  {
    module: 'Student Attendance',
    pageRoute: '/attendance',
    entityName: 'Daily Attendance',
    tableName: 'student_attendance',
    scopeMode: 'CAMPUS_REQUIRED',
    hasOrganizationId: true,
    hasSchoolId: true,
    hasCampusId: true,
    hasHierarchyAssignment: false,
    isWorkingContextApplied: true,
    isBackendEnforced: true,
    isDbPersisted: false,
    description: 'Daily student attendance records',
  },
];
